import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ScrollingAkiraText from "./ScrollingAkiraText";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NAV_ITEM_STYLE = {
  fontSize: "24px",
  fontFamily: "Ranga, cursive",
  color: "#000000",
  fontWeight: 900,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  height: "100%",
  textDecoration: "none"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Ranga:wght@400;700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Ranga:wght@400;700&family=Sedgwick+Ave+Display&display=swap" rel="stylesheet" />

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ background: "#1c1c1c" }}
      >
        {/* Full-width navbar stripe */}
        <nav
          className="w-full border-b border-black/[.08] dark:border-white/[.145] bg-white h-[200px] p-2"
        >
          {/* Centered navbar content container */}
          <div className="max-w-7xl mx-auto px-4 h-full flex items-center justify-between">
            <a
              href="/links"
              className="flex items-center justify-center font-bold"
              style={{
                fontSize: "24px",
                fontFamily: "Ranga, cursive",
                color: "#000000",
                height: "100%"
              }}
            >
              Links
            </a>
            <a
              href="/about"
              className="flex items-center justify-center font-bold"
              style={{
                fontSize: "24px",
                fontFamily: "Ranga, cursive",
                color: "#000000",
                height: "100%"
              }}
            >
              About
            </a>
            <a
              href="/"
              className="flex items-center justify-center"
              style={{
                height: "100%",
                padding: 0
              }}
            >
              <img
                src="/akira.webp"
                alt="akira"
                className="h-[100%]"
                style={{ margin: "0 auto" }}
              />
            </a>
            <a
              href="/blog"
              className="flex items-center justify-center font-bold"
              style={{
                fontSize: "24px",
                fontFamily: "Ranga, cursive",
                color: "#000000",
                height: "100%"
              }}
            >
              Blog
            </a>
            <a
              href="/contact"
              className="flex items-center justify-center font-bold"
              style={{
                fontSize: "24px",
                fontFamily: "Ranga, cursive",
                color: "#000000",
                height: "100%"
              }}
            >
              Contact
            </a>
          </div>
        </nav>
        {/* Scrolling background text with akira.webp image */}
        {/* Scrolling text - now a component */}
        <ScrollingAkiraText />
        {/* Page content container */}
        <div
          className="max-w-7xl mx-auto"
          style={{
            height: "calc(100vh - 200px)",
            overflow: "hidden",
            padding: "80px 24px"
          }}
        >
          <main
            className="flex flex-row h-full"
            style={{
            }}
          >
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
